<?php

namespace AppBundle\Repository;

/**
 * MenberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenberRepository extends \Doctrine\ORM\EntityRepository
{
}
