services:
#    main.example:
#        class: MainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  main.checker:
    class: MainBundle\Helper\Checker
    shared: false