main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
contact:
    path:     /{_locale}
    defaults: { _controller: MainBundle:Default:index }
    requirements:
        _locale: en|fr|de